# Generated by Django 3.2.9 on 2021-12-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('exteriorcolor', models.CharField(max_length=255)),
                ('interiorcolor', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('engineL', models.CharField(max_length=255)),
                ('sale', models.BooleanField()),
                ('carbrand', models.ManyToManyField(to='core.Carbrand')),
                ('carmodel', models.ManyToManyField(to='core.Carmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
