# Generated by Django 3.2.9 on 2021-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carobject',
            name='mileage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carobject',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
